name = "multiquant-bot"
main = "worker.mjs"
compatibility_date = "2026-09-30"
keep_vars = true

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "multiquant-db"
database_id = "f4070bcf-0584-4c57-8fcd-19ec5cf7d5e2"

[[durable_objects.bindings]]
name = "OKX_MONITOR"
class_name = "OkxMonitorDO"

[exports.OkxMonitorDO]
type = "durable-object"
storage = "sqlite"

[triggers]
crons = ["*/5 * * * *"]
